export const DUMMY_USERS_DATA = [
  {
    comment: "Not Action 'Invalid.  This was probably illegal",
    date: '04/09/2015 11:14 am',
    number: 123124,
    pvRule: 'N/A',
    status: 'Valid',
    user: 'MAlisha Allen',
  },
  {
    comment: "Action 'Invalid.  This was probably illegal",
    date: '04/09/2016 11:14 am',
    number: 123124,
    pvRule: 'N/A',
    status: 'Invalid',
    user: 'Alisha Pena',
  },
  {
    comment: "Not Action 'Invalid.  This was probably illegal",
    date: '04/09/2017 11:14 am',
    number: 123124,
    pvRule: 'N/A',
    status: 'Valid',
    user: 'Phil Pena',
  },
  {
    comment: "Action 'Invalid.  This was probably illegal",
    date: '04/09/2018 11:14 am',
    number: 123124,
    pvRule: 'N/A',
    status: 'Invalid',
    user: 'Alisha Phillips',
  },
  {
    comment: "Not Action 'Invalid.  This was probably illegal",
    date: '04/09/2011 11:14 am',
    number: 123124,
    pvRule: 'N/A',
    status: 'Valid',
    user: 'MAlisha Ashely',
  },
  {
    comment: "Action 'Invalid.  This was probably illegal",
    date: '04/09/2012 11:14 am',
    number: 123124,
    pvRule: 'N/A',
    status: 'Invalid',
    user: 'Pilot Pete',
  },
];
